name: Docker Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'
  repository_dispatch:
    types: ["Remote Trigger"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout recursively
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          # Username used to log against the Docker registry
          username: "${{secrets.DOCKER_HUB_USERNAME}}"
          # Password or personal access token used to log against the Docker registry
          password: "${{secrets.DOCKER_HUB_ACCESS_TOKEN}}"
          # Log out from the Docker registry at the end of a job
          logout: true

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: managah/jenkins-agent:latest
